
import fs from 'fs';
import path from 'path';

// Paths
const bexaltaSvgPath = '/Users/yolandy/Projects/00.HUEHUECÓYOTL/00.WORKING_PROJECTS/ANDY_FOUNDTECH/02-onepagers/bexalta/assets/logo_bexalta_white.svg';
const foundtechSvgPath = '/Users/yolandy/.gemini/antigravity/skills/foundtech-branding/assets/logos/2d/foundtech-logo-whitegreen.svg';
const outputPath = path.resolve('./src/assets/logos.js');

// Ensure output dir exists
const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

// Read and encode
const bexaltaSvg = fs.readFileSync(bexaltaSvgPath, 'utf8');
const foundtechSvg = fs.readFileSync(foundtechSvgPath, 'utf8');

const bexaltaBase64 = Buffer.from(bexaltaSvg).toString('base64');
const foundtechBase64 = Buffer.from(foundtechSvg).toString('base64');

// Create content
const content = `// Generated by generate_logos.js
export const BEXALTA_SVG = 'data:image/svg+xml;base64,${bexaltaBase64}';
export const FOUNDTECH_SVG = 'data:image/svg+xml;base64,${foundtechBase64}';
`;

// Write file
fs.writeFileSync(outputPath, content);
console.log(`Generated ${outputPath}`);
